# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhudu.github.io
date_format: "ordinal"
title: 未见青山老
subtitle: "愿得韶华刹那，开得满树芳华。"
description: "猪肚的个人博客"
keywords: 未见青山老, duxin Zhu, zhudu, zhuduxin
timezone: Asia/Xiamen
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: duxin Zhu
organization: 
organization_url: 
github_username: zhudu
location: Xiamen, China
email: nanyangbeihai@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhudu/zhudu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhudu
    repo: blog-comments
    oauth:
        client_id: 113a6ccf1f3271788c8d
        client_secret: 99ff60aab574286ccc5ecdf93f96dfe6b0223319
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhudu
    repo: blog-comments
    clientID: 113a6ccf1f3271788c8d
    clientSecret: 99ff60aab574286ccc5ecdf93f96dfe6b0223319
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
